/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.aMedievalHarvestFestival.frames;

import amedievalharvestfestival.AMedievalHarvestFestival;
import byui.cit260.aMedievalHarvestFestival.control.GameControl;
import static byui.cit260.aMedievalHarvestFestival.control.GameControl.greatestAmount;
import byui.cit260.aMedievalHarvestFestival.control.InventoryControl;
import byui.cit260.aMedievalHarvestFestival.model.InventoryItem;
import byui.cit260.aMedievalHarvestFestival.view.GameMenuView;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Kurt
 */
public class InventoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form InventoryFrame
     */
    public InventoryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInventoryBody = new javax.swing.JPanel();
        jpInventoryHeader = new javax.swing.JPanel();
        jlInventoryTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventoryItemList = new javax.swing.JTextArea();
        jbUseITem = new javax.swing.JButton();
        jbGreatestQuantity = new javax.swing.JButton();
        jbExitInventory = new javax.swing.JButton();
        jlExamine = new javax.swing.JLabel();
        jcItems = new javax.swing.JComboBox();
        jbExamine = new javax.swing.JButton();
        jcItems2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpInventoryBody.setBackground(new java.awt.Color(153, 255, 153));

        jpInventoryHeader.setBackground(new java.awt.Color(153, 255, 255));

        jlInventoryTitle.setFont(new java.awt.Font("Vivaldi", 2, 21)); // NOI18N
        jlInventoryTitle.setForeground(new java.awt.Color(0, 0, 204));
        jlInventoryTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlInventoryTitle.setText("Inventory Menu");

        javax.swing.GroupLayout jpInventoryHeaderLayout = new javax.swing.GroupLayout(jpInventoryHeader);
        jpInventoryHeader.setLayout(jpInventoryHeaderLayout);
        jpInventoryHeaderLayout.setHorizontalGroup(
            jpInventoryHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInventoryHeaderLayout.createSequentialGroup()
                .addComponent(jlInventoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpInventoryHeaderLayout.setVerticalGroup(
            jpInventoryHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInventoryHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInventoryTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtInventoryItemList.setEditable(false);
        jtInventoryItemList.setBackground(new java.awt.Color(204, 204, 255));
        jtInventoryItemList.setColumns(20);
        jtInventoryItemList.setLineWrap(true);
        jtInventoryItemList.setRows(5);
        jtInventoryItemList.setText("Inventory Items\n");
        jtInventoryItemList.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtInventoryItemList);

        jbUseITem.setText("Use Item");
        jbUseITem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUseITemActionPerformed(evt);
            }
        });

        jbGreatestQuantity.setText("Greatest Quanitiy");
        jbGreatestQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGreatestQuantityActionPerformed(evt);
            }
        });

        jbExitInventory.setText("Exit");
        jbExitInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitInventoryActionPerformed(evt);
            }
        });

        jlExamine.setText("Examine Item");

        jcItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcItemsActionPerformed(evt);
            }
        });

        jbExamine.setText("Examine");
        jbExamine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExamineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInventoryBodyLayout = new javax.swing.GroupLayout(jpInventoryBody);
        jpInventoryBody.setLayout(jpInventoryBodyLayout);
        jpInventoryBodyLayout.setHorizontalGroup(
            jpInventoryBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInventoryHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpInventoryBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpInventoryBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInventoryBodyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpInventoryBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInventoryBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbUseITem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbGreatestQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(jcItems, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlExamine)
                            .addComponent(jbExamine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcItems2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInventoryBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbExitInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jpInventoryBodyLayout.setVerticalGroup(
            jpInventoryBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInventoryBodyLayout.createSequentialGroup()
                .addComponent(jpInventoryHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInventoryBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInventoryBodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jpInventoryBodyLayout.createSequentialGroup()
                        .addComponent(jcItems2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbUseITem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlExamine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExamine)
                        .addGap(12, 12, 12)
                        .addComponent(jbGreatestQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExitInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInventoryBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInventoryBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUseITemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUseITemActionPerformed
        // TODO add your handling code here:
        InventoryItem item = (InventoryItem)jcItems2.getSelectedItem();
        showMessageDialog(null, InventoryControl.useItem(item));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbUseITemActionPerformed

    private void jbGreatestQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGreatestQuantityActionPerformed
        // TODO add your handling code here:
        showMessageDialog(null, greatestAmount(GameControl.getSortedInventoryList()));
    }//GEN-LAST:event_jbGreatestQuantityActionPerformed

    private void jbExitInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitInventoryActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbExitInventoryActionPerformed

    private void jcItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcItemsActionPerformed
        // TODO add your handling code here:
    
    
        
    }//GEN-LAST:event_jcItemsActionPerformed

    private void jbExamineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExamineActionPerformed
        // TODO add your handling code here:
        InventoryItem item = (InventoryItem)jcItems.getSelectedItem();
        showMessageDialog(null, item.getName() + "--" + item.getDescription());
    }//GEN-LAST:event_jbExamineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryFrame().setVisible(true);
            }
        });
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JButton getJbExitInventory() {
        return jbExitInventory;
    }

    public void setJbExitInventory(JButton jbExitInventory) {
        this.jbExitInventory = jbExitInventory;
    }

    public JButton getJbGreatestQuantity() {
        return jbGreatestQuantity;
    }

    public void setJbGreatestQuantity(JButton jbGreatestQuantity) {
        this.jbGreatestQuantity = jbGreatestQuantity;
    }

    public JButton getJbUseITem() {
        return jbUseITem;
    }

    public void setJbUseITem(JButton jbUseITem) {
        this.jbUseITem = jbUseITem;
    }

    public JLabel getJlInventoryTitle() {
        return jlInventoryTitle;
    }

    public void setJlInventoryTitle(JLabel jlInventoryTitle) {
        this.jlInventoryTitle = jlInventoryTitle;
    }

    public JPanel getJpInventoryBody() {
        return jpInventoryBody;
    }

    public void setJpInventoryBody(JPanel jpInventoryBody) {
        this.jpInventoryBody = jpInventoryBody;
    }

    public JPanel getJpInventoryHeader() {
        return jpInventoryHeader;
    }

    public void setJpInventoryHeader(JPanel jpInventoryHeader) {
        this.jpInventoryHeader = jpInventoryHeader;
    }

    public JTextArea getJtInventoryItemList() {
        return jtInventoryItemList;
    }

    public void setJtInventoryItemList(JTextArea jtInventoryItemList) {
        this.jtInventoryItemList = jtInventoryItemList;
    }

    public JComboBox getJcItems() {
        return jcItems;
    }

    public void setJcItems(JComboBox jcItems) {
        this.jcItems = jcItems;
    }

    public JLabel getJlExamine() {
        return jlExamine;
    }

    public void setJlExamine(JLabel jlExamine) {
        this.jlExamine = jlExamine;
    }

    public JButton getJbExamine() {
        return jbExamine;
    }

    public void setJbExamine(JButton jbExamine) {
        this.jbExamine = jbExamine;
    }

    public JComboBox getJcItems2() {
        return jcItems2;
    }

    public void setJcItems2(JComboBox jcItems2) {
        this.jcItems2 = jcItems2;
    }
    
    

    
    
    
    

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbExamine;
    private javax.swing.JButton jbExitInventory;
    private javax.swing.JButton jbGreatestQuantity;
    private javax.swing.JButton jbUseITem;
    private javax.swing.JComboBox jcItems;
    private javax.swing.JComboBox jcItems2;
    private javax.swing.JLabel jlExamine;
    private javax.swing.JLabel jlInventoryTitle;
    private javax.swing.JPanel jpInventoryBody;
    private javax.swing.JPanel jpInventoryHeader;
    private javax.swing.JTextArea jtInventoryItemList;
    // End of variables declaration//GEN-END:variables
}
