/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.aMedievalHarvestFestival.frames;

import amedievalharvestfestival.AMedievalHarvestFestival;
import byui.cit260.aMedievalHarvestFestival.control.GameControl;
import byui.cit260.aMedievalHarvestFestival.control.LocationControl;
import byui.cit260.aMedievalHarvestFestival.model.Location;

/**
 *
 * @author Kurt
 */
public class MoveLocationFrame extends javax.swing.JFrame {
    Location[][] locations = GameControl.getMapLocations();

    /**
     * Creates new form MoveLocationFrame
     */
    public MoveLocationFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLocationBody = new javax.swing.JPanel();
        jpLocationHeading = new javax.swing.JPanel();
        jlMoveLocationTitle = new javax.swing.JLabel();
        jbMyRoom = new javax.swing.JButton();
        jbLadyVioRoom = new javax.swing.JButton();
        jbDukeFredRoom = new javax.swing.JButton();
        jbDukeHaroRoom = new javax.swing.JButton();
        jbDukeLuisRoom = new javax.swing.JButton();
        jbLordCanaRoom = new javax.swing.JButton();
        jbEmptyRoom = new javax.swing.JButton();
        jbServantsQ = new javax.swing.JButton();
        jbPrinRoom = new javax.swing.JButton();
        jbKingRoom = new javax.swing.JButton();
        jbKingRestroom = new javax.swing.JButton();
        jbGardens = new javax.swing.JButton();
        jbStables = new javax.swing.JButton();
        jbCourtyard = new javax.swing.JButton();
        jbGuestRR = new javax.swing.JButton();
        jbKitchen = new javax.swing.JButton();
        jbAudCham = new javax.swing.JButton();
        jbDineHall = new javax.swing.JButton();
        jbLibrary = new javax.swing.JButton();
        jbPool = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpLocationBody.setBackground(new java.awt.Color(153, 255, 153));

        jpLocationHeading.setBackground(new java.awt.Color(153, 255, 255));

        jlMoveLocationTitle.setFont(new java.awt.Font("Vivaldi", 2, 21)); // NOI18N
        jlMoveLocationTitle.setForeground(new java.awt.Color(0, 0, 204));
        jlMoveLocationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMoveLocationTitle.setText("Move to a Location Menu");

        javax.swing.GroupLayout jpLocationHeadingLayout = new javax.swing.GroupLayout(jpLocationHeading);
        jpLocationHeading.setLayout(jpLocationHeadingLayout);
        jpLocationHeadingLayout.setHorizontalGroup(
            jpLocationHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLocationHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMoveLocationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLocationHeadingLayout.setVerticalGroup(
            jpLocationHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLocationHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMoveLocationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbMyRoom.setText("My Room");
        jbMyRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMyRoomActionPerformed(evt);
            }
        });

        jbLadyVioRoom.setText("Lady Violet's Room");
        jbLadyVioRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLadyVioRoomActionPerformed(evt);
            }
        });

        jbDukeFredRoom.setText("Duke Frederick's Room");
        jbDukeFredRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDukeFredRoomActionPerformed(evt);
            }
        });

        jbDukeHaroRoom.setText("Duke Harold's Room");
        jbDukeHaroRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDukeHaroRoomActionPerformed(evt);
            }
        });

        jbDukeLuisRoom.setText("Duke Luis' Room");
        jbDukeLuisRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDukeLuisRoomActionPerformed(evt);
            }
        });

        jbLordCanaRoom.setText("Lord Canaway's Room");
        jbLordCanaRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLordCanaRoomActionPerformed(evt);
            }
        });

        jbEmptyRoom.setText("Empty Room");
        jbEmptyRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmptyRoomActionPerformed(evt);
            }
        });

        jbServantsQ.setText("Servants' Quarters");
        jbServantsQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbServantsQActionPerformed(evt);
            }
        });

        jbPrinRoom.setText("Princess' Room");
        jbPrinRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrinRoomActionPerformed(evt);
            }
        });

        jbKingRoom.setText("King's Room");
        jbKingRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKingRoomActionPerformed(evt);
            }
        });

        jbKingRestroom.setText("King's Private Restroom");
        jbKingRestroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKingRestroomActionPerformed(evt);
            }
        });

        jbGardens.setText("Gardens");
        jbGardens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGardensActionPerformed(evt);
            }
        });

        jbStables.setText("Stables");
        jbStables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStablesActionPerformed(evt);
            }
        });

        jbCourtyard.setText("Courtyard");
        jbCourtyard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCourtyardActionPerformed(evt);
            }
        });

        jbGuestRR.setText("Guest's Restroom");
        jbGuestRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuestRRActionPerformed(evt);
            }
        });

        jbKitchen.setText("Kitchen");
        jbKitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKitchenActionPerformed(evt);
            }
        });

        jbAudCham.setText("Audience Chamber");
        jbAudCham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAudChamActionPerformed(evt);
            }
        });

        jbDineHall.setText("Dining Hall");
        jbDineHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDineHallActionPerformed(evt);
            }
        });

        jbLibrary.setText("Library");
        jbLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLibraryActionPerformed(evt);
            }
        });

        jbPool.setText("Pool");
        jbPool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPoolActionPerformed(evt);
            }
        });

        jbExit.setText("Cancel");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLocationBodyLayout = new javax.swing.GroupLayout(jpLocationBody);
        jpLocationBody.setLayout(jpLocationBodyLayout);
        jpLocationBodyLayout.setHorizontalGroup(
            jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLocationHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpLocationBodyLayout.createSequentialGroup()
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLocationBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbMyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbLadyVioRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDukeFredRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDukeHaroRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDukeLuisRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbLordCanaRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEmptyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbServantsQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPrinRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbKingRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCourtyard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGuestRR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbKitchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAudCham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDineHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbKingRestroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGardens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbStables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPool, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpLocationBodyLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLocationBodyLayout.setVerticalGroup(
            jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLocationBodyLayout.createSequentialGroup()
                .addComponent(jpLocationHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMyRoom)
                    .addComponent(jbKingRestroom))
                .addGap(4, 4, 4)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLadyVioRoom)
                    .addComponent(jbGardens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDukeFredRoom)
                    .addComponent(jbStables))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDukeHaroRoom)
                    .addComponent(jbCourtyard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDukeLuisRoom)
                    .addComponent(jbGuestRR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLordCanaRoom)
                    .addComponent(jbKitchen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEmptyRoom)
                    .addComponent(jbAudCham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbServantsQ)
                    .addComponent(jbDineHall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPrinRoom)
                    .addComponent(jbLibrary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocationBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKingRoom)
                    .addComponent(jbPool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLocationBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLocationBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLordCanaRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLordCanaRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[1][1]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbLordCanaRoomActionPerformed

    private void jbEmptyRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmptyRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[1][2]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbEmptyRoomActionPerformed

    private void jbPrinRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrinRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[1][4]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbPrinRoomActionPerformed

    private void jbKingRestroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKingRestroomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[2][1]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbKingRestroomActionPerformed

    private void jbStablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStablesActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[0][0]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbStablesActionPerformed

    private void jbLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLibraryActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[3][3]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbLibraryActionPerformed

    private void jbPoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPoolActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[3][4]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbPoolActionPerformed

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbMyRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMyRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[0][1]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbMyRoomActionPerformed

    private void jbLadyVioRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLadyVioRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[0][2]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbLadyVioRoomActionPerformed

    private void jbDukeFredRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDukeFredRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[0][3]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDukeFredRoomActionPerformed

    private void jbDukeHaroRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDukeHaroRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[0][4]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDukeHaroRoomActionPerformed

    private void jbDukeLuisRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDukeLuisRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[1][0]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDukeLuisRoomActionPerformed

    private void jbServantsQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbServantsQActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[1][3]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbServantsQActionPerformed

    private void jbKingRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKingRoomActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[2][0]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbKingRoomActionPerformed

    private void jbGardensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGardensActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[2][2]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbGardensActionPerformed

    private void jbCourtyardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCourtyardActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[2][3]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCourtyardActionPerformed

    private void jbGuestRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuestRRActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[2][4]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbGuestRRActionPerformed

    private void jbKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKitchenActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[3][0]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbKitchenActionPerformed

    private void jbAudChamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAudChamActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[3][1]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAudChamActionPerformed

    private void jbDineHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDineHallActionPerformed
        // TODO add your handling code here:
        AMedievalHarvestFestival.getGameMenu().getJtMessage().setText(LocationControl.movePlayerToLocation(locations[3][2]));
        AMedievalHarvestFestival.getGameMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDineHallActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAudCham;
    private javax.swing.JButton jbCourtyard;
    private javax.swing.JButton jbDineHall;
    private javax.swing.JButton jbDukeFredRoom;
    private javax.swing.JButton jbDukeHaroRoom;
    private javax.swing.JButton jbDukeLuisRoom;
    private javax.swing.JButton jbEmptyRoom;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbGardens;
    private javax.swing.JButton jbGuestRR;
    private javax.swing.JButton jbKingRestroom;
    private javax.swing.JButton jbKingRoom;
    private javax.swing.JButton jbKitchen;
    private javax.swing.JButton jbLadyVioRoom;
    private javax.swing.JButton jbLibrary;
    private javax.swing.JButton jbLordCanaRoom;
    private javax.swing.JButton jbMyRoom;
    private javax.swing.JButton jbPool;
    private javax.swing.JButton jbPrinRoom;
    private javax.swing.JButton jbServantsQ;
    private javax.swing.JButton jbStables;
    private javax.swing.JLabel jlMoveLocationTitle;
    private javax.swing.JPanel jpLocationBody;
    private javax.swing.JPanel jpLocationHeading;
    // End of variables declaration//GEN-END:variables
}
