/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.aMedievalHarvestFestival.frames;

import byui.cit260.aMedievalHarvestFestival.control.ProgramControl;
import byui.cit260.aMedievalHarvestFestival.model.Player;
import javax.swing.JOptionPane;

/**
 *
 * @author zev
 */
public class StartProgramFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartProgramFrame
     */
    public StartProgramFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jpMainPanel = new javax.swing.JPanel();
        jpHeader = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpWelcomeMessage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaWelcomeMessage = new javax.swing.JTextArea();
        jpForm = new javax.swing.JPanel();
        jbStartGame = new javax.swing.JButton();
        jbQuit = new javax.swing.JButton();
        jtfPlayerName = new javax.swing.JTextField();
        jlPromptName = new javax.swing.JLabel();
        jpMainImage = new javax.swing.JPanel();
        jlStartProgramImage = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMainPanel.setBackground(new java.awt.Color(153, 255, 153));
        jpMainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jpMainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpHeader.setBackground(new java.awt.Color(153, 255, 255));
        jpHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlTitle.setFont(new java.awt.Font("Vivaldi", 2, 36)); // NOI18N
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("A Medival Harvest Festival");

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(111, 111, 111))
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpWelcomeMessage.setBackground(new java.awt.Color(153, 255, 255));
        jpWelcomeMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtaWelcomeMessage.setEditable(false);
        jtaWelcomeMessage.setColumns(20);
        jtaWelcomeMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtaWelcomeMessage.setRows(5);
        jtaWelcomeMessage.setText("This is the game A Medieval Harvest Festival.\nIn this game you will take the role of Lord\nPharaoh, who was invited to the Williams' Castle.\nThe Princess has gone missing and you will have\nfind out what has happened to her.\n\nIn order to find where the Princess is and what\nhappened to her, you will have to explore the\ncastle, inside and out. You will have to\nexamine objects and various rooms in order to\nfind evidence. You will also have to talk to  \nvarious guests and servants in order to find\nout key pieces of information that will also\nserve as evidence. As you are looking for clues\nyou will have to keep Lord Pharaoh fed and\nquenched.\n\nMay thy journey fare thee well!");
        jtaWelcomeMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaWelcomeMessage);

        javax.swing.GroupLayout jpWelcomeMessageLayout = new javax.swing.GroupLayout(jpWelcomeMessage);
        jpWelcomeMessage.setLayout(jpWelcomeMessageLayout);
        jpWelcomeMessageLayout.setHorizontalGroup(
            jpWelcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWelcomeMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpWelcomeMessageLayout.setVerticalGroup(
            jpWelcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWelcomeMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpForm.setBackground(new java.awt.Color(153, 255, 255));
        jpForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbStartGame.setText("Start");
        jbStartGame.setToolTipText("Start Game!");
        jbStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartGameActionPerformed(evt);
            }
        });

        jbQuit.setText("Quit");
        jbQuit.setToolTipText("Quit Game");
        jbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitActionPerformed(evt);
            }
        });

        jtfPlayerName.setToolTipText("Enter name here");

        jlPromptName.setText("Enter your name and select Start button.");

        javax.swing.GroupLayout jpFormLayout = new javax.swing.GroupLayout(jpForm);
        jpForm.setLayout(jpFormLayout);
        jpFormLayout.setHorizontalGroup(
            jpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpFormLayout.createSequentialGroup()
                        .addComponent(jbStartGame)
                        .addGap(18, 18, 18)
                        .addComponent(jbQuit))
                    .addComponent(jtfPlayerName)
                    .addComponent(jlPromptName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFormLayout.setVerticalGroup(
            jpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPromptName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbStartGame)
                    .addComponent(jbQuit))
                .addGap(16, 16, 16))
        );

        jpMainImage.setBackground(new java.awt.Color(153, 255, 255));
        jpMainImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlStartProgramImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStartProgramImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/byui/cit260/aMedievalHarvestFestival/images/castleart.jpg"))); // NOI18N

        javax.swing.GroupLayout jpMainImageLayout = new javax.swing.GroupLayout(jpMainImage);
        jpMainImage.setLayout(jpMainImageLayout);
        jpMainImageLayout.setHorizontalGroup(
            jpMainImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlStartProgramImage, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMainImageLayout.setVerticalGroup(
            jpMainImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlStartProgramImage, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMainPanelLayout = new javax.swing.GroupLayout(jpMainPanel);
        jpMainPanel.setLayout(jpMainPanelLayout);
        jpMainPanelLayout.setHorizontalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpMainPanelLayout.createSequentialGroup()
                        .addComponent(jpMainImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMainPanelLayout.setVerticalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpWelcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMainImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartGameActionPerformed
        // get player's name
        String playersName = this.jtfPlayerName.getText();
//        trim excess blanks
       playersName = playersName.trim();
//        check for if greater than 1 character 
       if (playersName.length() < 1) {
           JOptionPane.showMessageDialog(this, "Player's name must be longer than one character", "Invalid Player Name", JOptionPane.ERROR_MESSAGE);
            return;
       }
//        create the player
//        create the player object and save it to the ProgramControl class
        Player player = ProgramControl.createPlayer(playersName);
//        create the main frame
        MainFrame mainFrame = new MainFrame();
        mainFrame.jtWelcome.setText("Welcome to the game " + player.getName() + "! Have a good time! It is "
                + "recommended that first time players visit the \"How to Play\" menu.");
        mainFrame.setVisible(true);
//        set the welcome message on the MainFrame
//        display the main frame
        
//        Dispose of this frame
        this.dispose();
    
    }//GEN-LAST:event_jbStartGameActionPerformed

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbQuitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbQuit;
    private javax.swing.JButton jbStartGame;
    private javax.swing.JLabel jlPromptName;
    private javax.swing.JLabel jlStartProgramImage;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpForm;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpMainImage;
    private javax.swing.JPanel jpMainPanel;
    private javax.swing.JPanel jpWelcomeMessage;
    private javax.swing.JTextArea jtaWelcomeMessage;
    private javax.swing.JTextField jtfPlayerName;
    // End of variables declaration//GEN-END:variables
}
